specVersion: 0.2.0
name: salp-confirm-bifrost-subql
version: 1.0.0
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-bifrost-subql.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x262e1b2ad728475fd6fe88e62d34c200abe6fd693931ddad144059b1eb884e5b'
  endpoint: wss://hk.p.bifrost-rpc.liebi.com/ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 725700
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: salp
          kind: substrate/BlockHandler
        - handler: handleSalpContributing
          kind: substrate/EventHandler
          filter:
            module: salp
            method: Contributing
        - handler: handleSalpContributed
          kind: substrate/EventHandler
          filter:
            module: salp
            method: Contributed
        - handler: handleSalpContributeFailed
          kind: substrate/EventHandler
          filter:
            module: salp
            method: ContributeFailed
